# Generated by Django 4.2.2 on 2023-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socis',
            fields=[
                ('soci_id', models.AutoField(primary_key=True, serialize=False)),
                ('soci_nom', models.CharField(max_length=100)),
                ('soci_curs', models.CharField(max_length=5)),
                ('soci_direccio', models.CharField(max_length=100)),
                ('soci_codi_postal', models.IntegerField()),
                ('soci_ciutat', models.CharField(max_length=50)),
                ('soci_telefon', models.CharField(max_length=15)),
                ('soci_email', models.EmailField(max_length=254)),
                ('soci_drets_imatge', models.BooleanField()),
                ('soci_drets_whatzap', models.BooleanField()),
                ('soci_cc', models.CharField(max_length=25)),
                ('soci_nom_pares', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Soci',
                'verbose_name_plural': 'Socis',
                'ordering': ['-soci_nom'],
            },
        ),
    ]
