# Generated by Django 4.2.2 on 2023-06-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importar',
            fields=[
                ('importar_id', models.AutoField(primary_key=True, serialize=False)),
                ('importar_ruta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Importar',
                'verbose_name_plural': 'Importacions',
            },
        ),
    ]
