# Generated by Django 4.2.2 on 2023-06-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0002_importar'),
    ]

    operations = [
        migrations.AddField(
            model_name='importar',
            name='importar_nom',
            field=models.FileField(default=111, upload_to='socis/csv', verbose_name='Csv'),
            preserve_default=False,
        ),
    ]
